### PR TITLE
compressed the size and quality of images

### PR DESCRIPTION
**Pull request by PranK14**
jwoc

### CODE REVIEW

**Comment by skpandey885** [comment]
Please publish your changes to a website. Send me the link of that. 
For reference: 
```
https://github.com/skpandey885/HealhUb/blob/main/Documentation/Publish-your-changes.md
```

**Comment by PranK14** [comment]
okayy

**Comment by PranK14** [comment]
@skpandey885  https://prank14.github.io/HealhUb/

**Comment by skpandey885** [comment]
@PranK14 
The following Images you have missed to compress: 
1 photo from the home page- (Man Running)
Background Image of Covid Section 

The background image is not displaying in this page 👇🏻
```
https://prank14.github.io/HealhUb/pages/about.html
```

Fix all this and add commits to this PR

**Comment by PranK14** [comment]
okay

**Comment by PranK14** [comment]
@skpandey885 pls check

**Comment by skpandey885** [comment]
Which tool you have used to compress the images?

The quality of the background image in this link 👇🏻 has been drastically reduced. You do one thing, leave this image, keep it unchanged, and don't compress this particular bg image, leave it as it is and commit.
```
https://prank14.github.io/HealhUb/pages/about.html
```

**Comment by PranK14** [comment]
@skpandey885  srry for not able to compress bg correctly i think i have restored it pls check https://prank14.github.io/HealhUb/pages/about.html

**Pull request merged**
