### PR TITLE
Made the blog footer responsive

### PR DESCRIPTION
**Pull request by Tess-Vanta**
### Changes made:
- [x] Made the footer of "Blogs & Articles" page responsive
- [x] Added icons to the contacts in the footer

### Snapshot
image

### Link
https://tess-vanta.github.io/HealhUb/pages/cards.html

### CODE REVIEW

**Comment by skpandey885** [comment]
You have changed the orientation of these cards? why?
Screenshot 2022-02-05 at 9 13 49 PM

**Comment by skpandey885** [comment]
You have also changed the navbar. That was not needed.
See the navbars of these pages & find the difference 👇🏻
https://tess-vanta.github.io/HealhUb/pages/cards.html
https://skpandey885.github.io/HealhUb/pages/cards.html

**Comment by Tess-Vanta** [comment]
oh sorry, i havent noticed. Ill fix it.

**Comment by Tess-Vanta** [comment]
I have made the change could you check ? 
https://tess-vanta.github.io/HealhUb/pages/cards.html

**Comment by skpandey885** [comment]
Try to check the responsiveness @ dimensions near 320. Its not perfect
Screenshot 2022-02-05 at 11 21 13 PM

**Comment by Tess-Vanta** [comment]
I have made the change. Could you check now?
https://tess-vanta.github.io/HealhUb/pages/cards.html

**Pull request merged**
