### PR TITLE
updated issue #130

### PR DESCRIPTION
**Pull request by aksharma27**
resolved issue #130

### CODE REVIEW

**Comment by skpandey885** [comment]
Hey @aksharma27 ! Please give me a link to the site where I can see your changes. If you don't know how to create a link, refer [this](https://github.com/skpandey885/HealhUb/blob/main/Documentation/Publish-your-changes.md).

**Comment by skpandey885** [comment]
Hey @aksharma27, what is the update?

**Comment by aksharma27** [comment]
> 

http://abhishekmjm.me/HealhUb/pages/bodyFat.html

**Comment by aksharma27** [comment]
IMG_20221004_113725

This one is original (before my changes)

**Comment by aksharma27** [comment]
Screenshot_2022-10-04-11-33-52-825_com android chrome


And this one after my changes.

**Pull request merged**
