### PR TITLE
Add Dark Theme with Toggle Button

### PR DESCRIPTION
**Pull request by YatharthaRana**
I have added a toggle button 
Also the choice for theme got saved so that it remains even after reloading the page.

### CODE REVIEW

**Comment by skpandey885** [comment]
Hey @YatharthaRana! When i visited to the "Teams" page the toggle button dissapeared. Can you please check it.

Screenshot 2022-10-06 at 9 12 35 PM

**Comment by YatharthaRana** [comment]
Hello @skpandey885, Actually the background of "teams" page is image, so the image can't be changed into dark mode
That's why I didn't apply toggle button on that page.

If you have any suggestions on what can be changed when switching to dark mode, I will apply it on this page too..

**Comment by skpandey885** [comment]
> Hello @skpandey885, Actually the background of "teams" page is image, so the image can't be changed into dark mode That's why I didn't apply toggle button on that page.
> 
> If you have any suggestions on what can be changed when switching to dark mode, I will apply it on this page too..

Hey, I told you that please pull the repo because the team page has been completely changed.
You check click [here](https://healhub.vercel.app/pages/team-members.html) and see the new page.

**Comment by YatharthaRana** [comment]
> > Hello @skpandey885, Actually the background of "teams" page is image, so the image can't be changed into dark mode That's why I didn't apply toggle button on that page.
> > If you have any suggestions on what can be changed when switching to dark mode, I will apply it on this page too..
> 
> Hey, I told you that please pull the repo because the team page has been completely changed. You check click [here](https://healhub.vercel.app/pages/team-members.html) and see the new page.

@skpandey885 Done the changes

**Review by skpandey885 — APPROVED** [review]
Good Job @YatharthaRana!

**Pull request merged**
