### PR TITLE
Improved the documentation.

### PR DESCRIPTION
**Pull request by kaal-coder**
Added and renamed some of the sections in README.md

### CODE REVIEW

**Comment by skpandey885** [comment]
@kaal-coder Can you please share some screenshots/instances? It will make things more clear.

**Comment by kaal-coder** [comment]
https://github.com/kaal-coder/HealhUb
You can view it here !

**Comment by skpandey885** [comment]
@kaal-coder Amazing work Buddy.

Some things which need more improvement are:

**Make the title bold and bigger "Tools Available" & "Covid 19 Stats"**

Screenshot 2022-04-22 at 10 51 14 PM
Screenshot 2022-04-22 at 10 51 32 PM


**Currently this section is vertically aligned. Try to keep 2 people's names in one row.
Total rows - 2 
In each row, there will be the names of 2 people.**

Screenshot 2022-04-22 at 10 51 59 PM



Also, please reduce the dimensions(size) of every screenshot/glimpses from the website which are added in the readme. Also reduce the dimensions(size) of the video recording added in the readme.

**Comment by kaal-coder** [comment]
Okay Buddy ! All this will be done before Sunday (24.04.2022).
Will that be okay ?

**Comment by skpandey885** [comment]
> Okay Buddy ! All this will be done before Sunday (24.04.2022). Will that be okay ? And you can Assign me in the [issue](https://github.com/skpandey885/HealhUb/issues/118) 😅

Still, the changes are not fixed. Make them bold and bigger

Screenshot 2022-04-23 at 4 56 41 PM
Screenshot 2022-04-23 at 4 56 51 PM

**Comment by kaal-coder** [comment]
Yes yes, the work isn't completed. I'll put a PR when everything is done!

**Comment by skpandey885** [comment]
> Yes yes, the work isn't completed. I'll put a PR when everything is done!

cool

**Pull request closed without merging**
