### PR TITLE
Improved the Responsiveness of the Covid Section #56

### PR DESCRIPTION
**Pull request by Mainakroy050**
issue : https://github.com/skpandey885/HealhUb/issues/56
live preview : https://mainakroy050.github.io/HealhUb/
image
Screenshot (124)
-

### CODE REVIEW

**Comment by skpandey885** [comment]
The Page is not Responsive. There are lots of errors.
Screenshot 2022-02-12 at 5 19 51 PM

**Comment by skpandey885** [comment]
**IT IS STILL NOT RESPONSIVE**

https://user-images.githubusercontent.com/78532081/153752796-cc48a3cc-f0b7-4cca-bd5f-9569afd6d2a6.mov

**Comment by Mainakroy050** [comment]
hey! sorry for the delay actually I was traveling. please check the changes.

**Comment by skpandey885** [comment]
Still, It is not responsive and not according to the Mobile View. I am closing this PR. You have taken a lot of time
Screenshot 2022-02-14 at 10 07 20 PM

**Pull request closed without merging**
