### PR TITLE
fix:#117 Add some margin✌️

### PR DESCRIPTION
**Pull request by Pritam0077**
Added the margin that was mentioned in the issue

### CODE REVIEW

**Comment by Pritam0077** [comment]
Here's the link https://pritam0077.github.io/HealhUb/

**Comment by Pritam0077** [comment]
i have modified the margin and commited the changes

**Comment by skpandey885** [comment]
> do I need to push the commits again?

yes

**Comment by Pritam0077** [comment]
done

**Comment by skpandey885** [comment]
> done

Good Job

**Pull request merged**
