### PR TITLE
feat: added calorie calculator page

### PR DESCRIPTION
**Pull request by mridul4101**
In response to issue #95.

Closes: #95

The calorie count is calculated by an average of two different measures:
- Mifflin-St Jeor Equation
- Revised Harris-Benedict Equation

Find the deployed site here: https://mridul4101.github.io/HealhUb/pages/calorie.html

### CODE REVIEW

**Comment by skpandey885** [comment]
Refer this: https://github.com/skpandey885/HealhUb/blob/main/Documentation/Publish-your-changes.md

**Comment by mridul4101** [comment]
Okay

**Comment by skpandey885** [comment]
Screenshot 2022-03-05 at 12 47 10 PM

Give some margin between the div and navbar.

**Comment by skpandey885** [comment]
Give a heading as "Calorie Calculator" Just above the box

**Pull request merged**
