### PR TITLE
Improved card styling and add more cards 

### LINKED ISSUE #11: Improve card sizing and add more cards
**Current Behaviour:**  In the Blogs & Articles page we have used Bootstrap cards. The size of each card is not the same.
You can Refer: https://skpandey885.github.io/HealhUb/pages/cards.html

Screenshot 2022-02-01 at 9 21 55 AM
<hr>

**Expected Behaviour:** Make all the cards of the same size and add more cards(with different article links and photos).

### PR DESCRIPTION
**Pull request by mgjain9871**
Fixes #11 

BEFORE: 
image

AFTER:
image

### CODE REVIEW

**Comment by skpandey885** [comment]
@mgjain9871 Give the link

**Comment by mgjain9871** [comment]
https://mgjain9871.github.io/HealhUb/pages/cards.html
@skpandey885

**Comment by skpandey885** [comment]
Hey. @mgjain9871 Great work but add more cards to it. Add 6-9 cards to it.

**Comment by mgjain9871** [comment]
Ok, will add some more cards by tomorrow.

**Comment by skpandey885** [comment]
You haven't followed the steps given in 👇🏻
`https://github.com/skpandey885/HealhUb/blob/main/README.md`

**Comment by skpandey885** [comment]
> https://github.com/skpandey885/HealhUb/blob/main/README.md

I am merging the PR for now. But never do this mistake again. Always create a separate branch.

**Comment by mgjain9871** [comment]
Sure @skpandey885, I will take care of that from next time.
Please assign the medium and JWOC labels to this PR.

**Pull request merged**
