### PR TITLE
Improved the documentation.

### PR DESCRIPTION
**Pull request by kaal-coder**
Some sections have been added, some renamed. 
The image and video size when reduced doesn't gives a good luck. Hence they are kept in the default size.

### CODE REVIEW

**Comment by kaal-coder** [comment]
Sorry, couldn't get @skpandey885.

**Comment by skpandey885** [comment]
Can you send me some screenshots

**Comment by kaal-coder** [comment]
Ohh understood. 
https://github.com/kaal-coder/HealhUb

**Comment by kaal-coder** [comment]
@skpandey885 Everything ok for my PR to get accepted ?

**Comment by skpandey885** [comment]
> @skpandey885 Everything ok for my PR to get accepted ?

yupp

**Pull request merged**
