### PR TITLE
Added Nearby-Hospitals page.

### PR DESCRIPTION
**Pull request by DarkFalc0n**
#66 
[Link to the hosted page](https://darkfalc0n.github.io/HealhUb/)
The nearby hospitals page needs a Google Maps API key. The API key must be generated from Google Maps Platform. For the Map to work, your API key must have these services/APIs enabled and also must have billing option enabled.
image
The API key must be placed in [/js/hospitalmap.js](https://github.com/DarkFalc0n/HealhUb/blob/main/js/hospitalmap.js) in the place of `API_KEY_HERE`

### CODE REVIEW

**Comment by skpandey885** [comment]
Please mention the issue number with the link.
If you don't know how to create a link refer to this-
https://github.com/skpandey885/HealhUb/blob/main/Documentation/Publish-your-changes.md

**Comment by DarkFalc0n** [comment]
> Please mention the issue number with the link. If you don't know how to create a link refer to this- https://github.com/skpandey885/HealhUb/blob/main/Documentation/Publish-your-changes.md

added a link

**Comment by skpandey885** [comment]
What can we do to fix this?
Screenshot 2022-02-21 at 6 58 41 PM

**Comment by DarkFalc0n** [comment]
> What can we do to fix this? Screenshot 2022-02-21 at 6 58 41 PM

I cant reveal my API as I have a personal project set up without billing.
There is currently only one fix for this, and that is to generate your own API key by creating a new public project set up in your Google Maps account. 
This is the reason I asked for an API key from you. API keys should not be put in public repositories as they can be detected and misused by bots scraping github repositories for API keys. For now, it is best that you generate one of your own and then run it from the local machine. For the final production, I would suggest the use of environment variables in the hosting service. I hope you are familiar with using process.env usage.

**Comment by skpandey885** [comment]
Ok. Cool

**Pull request closed without merging**
