### PR TITLE
Bmi page modify

### PR DESCRIPTION
**Pull request by YatharthaRana**
Age and Gender do affect the BMI.
As children grow at different rates, there is a difference in females' and males' weight for the same height.

### CODE REVIEW

**Comment by skpandey885** [comment]
Hey @YatharthaRana ! Please give me a link to the site where I can see your changes. If you don't know how to create a link, refer [this](https://github.com/skpandey885/HealhUb/blob/main/Documentation/Publish-your-changes.md).

**Comment by YatharthaRana** [comment]
https://yathartharana.github.io/HealhUb/

Here it is

**Review by skpandey885 — CHANGES_REQUESTED** [review]
Hey! I entered Negative age (which is not possible practically), there should be a popup or alert for it.

Screenshot 2022-10-01 at 11 57 07 PM

**Comment by YatharthaRana** [comment]
Screenshot 2022-10-02 at 00 48 50

Done

**Review by skpandey885 — CHANGES_REQUESTED** [review]
Hey, @YatharthaRana! Please fix these and i will merge the PR!
Remove those incrementers and decrementers from all the text-boxes 
Screenshot 2022-10-02 at 11 29 51 AM

**Comment by YatharthaRana** [comment]
Screenshot 2022-10-02 at 12 19 55

Removed the buttons

**Review by skpandey885 — APPROVED** [review]
All the changes you have made to the project are Okey and Good to go for a merge.

**Pull request merged**
