### PR TITLE
Improved Frontend

### PR DESCRIPTION
**Pull request by sumitkr2000**
Hey @skpandey885 This is pull request with reference to issue no #134.

I have made some minor changes in navbar and footer and a major change in BMI page. Some changes I made are listed below:

- Added styles in buttons on home page.

Before:-

Screenshot (335)

After:-

Screenshot (336)

- Added font awesome icons to navbar and added transition effect.

Before:-

Screenshot (333)

After:-

Screenshot (334)

- Added transition in the red underlines in footer. Now when we hover over it it changes it width.

Before:-

Screenshot (337)

After:- (Expand on hover)

Screenshot (338)

- Reformed the BMI page as there were some bugs in it. Also added styling by adding hover effect.

Before:- (Some data was not visible in desktop. Now I have added the data in the card itself.)

Screenshot (340)

After:-

Screenshot (339)

I have also added the link where you can see all the changes I hade made.

https://sumitkr2000.github.io/HealhUb/

Please merge my PR so that user experience will be improved. Thank you!

### CODE REVIEW

**Review by skpandey885 — CHANGES_REQUESTED** [review]
Hey @sumitkr2000, Great Job man! But I can't see other pages except home page, fix this and let me know ASAP👇🏻
<br>
Screenshot 2022-10-04 at 10 24 37 AM

**Comment by skpandey885** [comment]
This Link (https://sumitkr2000.github.io/HealhUb/) is redirecting me to another site, can you please check and give me another link or fix this.

**Comment by sumitkr2000** [comment]
@skpandey885 wait i am publishing another website. I am working on that. I had made a silly mistake in index.html page. Now i have corrected it.

**Comment by sumitkr2000** [comment]
Hey @skpandey885 I have successfully deployed the site and everything is working fine. Check this out:-

https://sumitkr2000.github.io/HealhUb/index.html

**Review by skpandey885 — APPROVED** [review]
Okey, Good to go!

**Pull request merged**
