### PR TITLE
fixed about page

### PR DESCRIPTION
**Pull request by ahmadjubair33**
Hi, @skpandey885 I have fixed the issue whatever possible with me. Please review it If possible merge it. Thank You 
#103

### CODE REVIEW

**Comment by skpandey885** [comment]
Please add the link. Go through this: https://github.com/skpandey885/HealhUb/blob/main/Documentation/Publish-your-changes.md

**Comment by ahmadjubair33** [comment]
@skpandey885 Here is tha link :  https://ahmadjubair33.github.io/HealhUb/

**Comment by skpandey885** [comment]
The changes you made are not satisfactory. Add something else instead of this.👇🏻
Screenshot 2022-03-08 at 9 55 22 AM

**Comment by skpandey885** [comment]
Do It ASAP.

**Comment by ahmadjubair33** [comment]
Hi @skpandey885 I have done from my side.if Still You want any change you can do after merging my pr.

**Pull request closed without merging**
