### PR TITLE
Changes in CSS of medical help

### PR DESCRIPTION
**Pull request by riiyaaa**
Added animated border and linear background.
closes issue #75 
link:  [issue 75](https://riiyaaa.github.io/HealhUb/) <br>
heal
<br>
heal2

### CODE REVIEW

**Comment by skpandey885** [comment]
Please mention the issue number with the link.
If you don't know how to create a link refer to this-
https://github.com/skpandey885/HealhUb/blob/main/Documentation/Publish-your-changes.md

**Comment by skpandey885** [comment]
Screenshot 2022-02-23 at 8 38 13 AM

Improve the font of this and add images for each disease.

**Comment by riiyaaa** [comment]
> Screenshot 2022-02-23 at 8 38 13 AM
> 
> Improve the font of this and add images for each disease.

Alright! I will make a pr by tomorrow evening.

**Comment by skpandey885** [comment]
> > Screenshot 2022-02-23 at 8 38 13 AM
> > Improve the font of this and add images for each disease.
> 
> Alright! I will make a pr by tomorrow evening.

Make the PR by tonight evening. You have already taken so much time. We are not allowed to give more than 2 days for a Medium level issue. Still, i gave you so much time. Make a pr by tonight.

**Comment by riiyaaa** [comment]
Images added and font changed. <br>
disease

**Comment by skpandey885** [comment]
You made this change in Main Branch Why????? I cannot accept this PR. Sorry.

**Pull request closed without merging**
