### PR TITLE
changes in ux and minor changes in ui

### PR DESCRIPTION
**Pull request by AnanyaM007**

### CODE REVIEW

**Comment by skpandey885** [comment]
Hey @AnanyaM007, the UX is still laggy! Can you modify the whole UI and change it? But it should be better than the current UI (It should be better than current one)

**Comment by AnanyaM007** [comment]
Hey Can you please tell me exactly which part of the website you feel is laggy...?
And yes I can change the UI. 
I will be working on this.

**Comment by AnanyaM007** [comment]
hey @skpandey885 I've made certain changes in ui. Please verify and lemme know if you need some other.

**Comment by AnanyaM007** [comment]
Hey @skpandey885 I've made certain changes. Please verify and lemme know if u need more

**Comment by skpandey885** [comment]
Hey @AnanyaM007! Can you add a text in small fonts. "Scroll to see more" at this position. Please let me know after you do it.
Screenshot 2022-10-09 at 7 03 26 PM

**Comment by AnanyaM007** [comment]
I've made the above mentioned changes. Please verify

**Review by skpandey885 — APPROVED** [review]

**Pull request merged**
