### PR TITLE
Improve about page

### PR DESCRIPTION
**Pull request by codervivek5**
I have added more content for the improvement of the about section.

### CODE REVIEW

**Comment by skpandey885** [comment]
Share the link of the changes you made.

**Comment by codervivek5** [comment]
How i conflict with tha basw branch

**Comment by skpandey885** [comment]
Read this: 
```
https://github.com/skpandey885/HealhUb/blob/main/Documentation/Publish-your-changes.md
```

**Comment by skpandey885** [comment]
hey @codervivek5. You have to add content in all sections of the "About" Page. You have only added  content in one section. Please make the necessary changes and add to this PR.

**Comment by codervivek5** [comment]
This is the link:
we have added some contact regarding the about us page
https://codervivek5.github.io/HealhUb/

**Comment by codervivek5** [comment]
> hey @codervivek5. You have to add content in all sections of the "About" Page. You have only added content in one section. Please make the necessary changes and additions to this PR.

one section means without changing paragraph like this

**Comment by codervivek5** [comment]
@skpandey885 I will add FAQ Questions and content to the privacy policy section.

**Pull request closed without merging**
