### PR TITLE
Hacktober branch

### PR DESCRIPTION
**Pull request by aksharma27**
issue #133 resolved
before
after

### CODE REVIEW

**Comment by skpandey885** [comment]
Hey @aksharma27  ! Please give me a link to the site where I can see your changes. If you don't know how to create a link, refer [this](https://github.com/skpandey885/HealhUb/blob/main/Documentation/Publish-your-changes.md).

**Comment by skpandey885** [comment]
Link?

**Comment by skpandey885** [comment]
Hey @aksharma27, please provide the link

**Comment by aksharma27** [comment]
https://healhubgit.netlify.app/pages/bodyfat

Sorry for the delay.

**Comment by aksharma27** [comment]
How do I resolve those conflicts?

**Pull request closed without merging**
