### PR TITLE
Pre loader | Issue #14 | https://ankit62042.github.io/HealhUb/

### PR DESCRIPTION
**Pull request by Ankit62042**
https://user-images.githubusercontent.com/71378462/152638072-2704e44f-8d9e-460b-a3e3-3e3ea082e6ba.mp4

### CODE REVIEW

**Comment by skpandey885** [comment]
@Ankit62042 Please add link  and issue number

**Comment by Ankit62042** [comment]
> @Ankit62042 Please add link and issue number

Done !!

**Comment by skpandey885** [comment]
@Ankit62042  Please go through this👇🏻
https://github.com/skpandey885/HealhUb/blob/main/Documentation/Publish-your-changes.md

**Comment by skpandey885** [comment]
The preloader is not showing. @Ankit62042

**Pull request closed without merging**
