### PR TITLE
Redesigned the covid page

### PR DESCRIPTION
**Pull request by Tess-Vanta**
### Changes made:
- Redesigned the page
- Made the page responsive
- Added the covid tracking api

### Snapshot
https://tess-vanta.github.io/HealhUb/

### CODE REVIEW

**Comment by skpandey885** [comment]
Multiple changes are required. Ping me when you are up for meet. ASAP

**Comment by Tess-Vanta** [comment]
Could you check if I missed anything

**Comment by skpandey885** [comment]
Please improve the CSS of this. Its really not looking good.

**Comment by Tess-Vanta** [comment]
> 
> Please improve the CSS of this.(Covid tracking) Its really not looking good.

Okays

**Comment by Tess-Vanta** [comment]
Check now

**Pull request merged**
